### ISSUE TITLE
PoolTimeout exception: Hishel doesn't close connections when using connection pool

### ISSUE THREAD

**Issue by hnesk** [karosis88/hishel#82]
Hishel breaks httpx connection pool mechanism by not closing the connections.

Without hishel [`httpx._transports.default.ResponseStream.close()`](https://github.com/encode/httpx/blob/3ba5fe0d7ac70222590e759c31442b1cab263791/httpx/_transports/default.py#L115) calls [`httpcore._sync.connection_pool.ConnectionPoolByteStream.close()`](https://github.com/encode/httpcore/blob/b7d2af60a2df8db751c59fc2c32642f0ea2602b5/httpcore/_sync/connection_pool.py#L350) which then releases the connection from the pool via a call to `response_closed()`. 

With hishel the `_httpcore_stream` attribute in [`httpx._transports.default.ResponseStream.close()`](https://github.com/encode/httpx/blob/3ba5fe0d7ac70222590e759c31442b1cab263791/httpx/_transports/default.py#L115) is just the generator from [`fake_stream`](https://github.com/karosis88/hishel/blob/630ae92244aff0340322a099716a6bcfe905bc4b/hishel/_sync/_transports.py#L24), which doesn't have a meaningful `close()` method.

To reproduce:

```python
import httpx
import hishel

# Extra low limits to trigger the bug immediately, default are 100 connections
limits=httpx.Limits(max_connections=1, max_keepalive_connections=0)

# PoolTimeout exception with hishel
client = hishel.CacheClient(limits=limits)

# Default httpx Client works
#client = httpx.Client(limits=limits)

for i in range(2):
    res = client.get('https://httpbin.org/base64/SFRUUEJJTiBpcyBhd2Vzb21l')
    print(i, res.text)

```
---
```
0 HTTPBIN is awesome
Traceback (most recent call last):
  File "/home/jk/Projekte/rats-transscript/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
    yield
  File "/home/jk/Projekte/rats-transscript/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
  File "/home/jk/Projekte/rats-transscript/venv/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 242, in handle_request
    raise exc
  File "/home/jk/Projekte/rats-transscript/venv/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 233, in handle_request
    connection = status.wait_for_connection(timeout=timeout)
  File "/home/jk/Projekte/rats-transscript/venv/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 35, in wait_for_connection
    self._connection_acquired.wait(timeout=timeout)
  File "/home/jk/Projekte/rats-transscript/venv/lib/python3.10/site-packages/httpcore/_synchronization.py", line 252, in wait
    raise PoolTimeout()  # pragma: nocover
httpcore.PoolTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jk/Projekte/rats-transscript/test-cache.py", line 14, in <module>
    res = client.get('https://httpbin.org/base64/SFRUUEJJTiBpcyBhd2Vzb21l')
  File "/home/jk/Projekte/rats-transscript/venv/lib/python3.10/site-packages/httpx/_client.py", line 1041, in get
    return self.request(
  File "/home/jk/Projekte/rats-transscript/venv/lib/python3.10/site-packages/httpx/_client.py", line 814, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/jk/Projekte/rats-transscript/venv/lib/python3.10/site-packages/httpx/_client.py", line 901, in send
    response = self._send_handling_auth(
  File "/home/jk/Projekte/rats-transscript/venv/lib/python3.10/site-packages/httpx/_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/home/jk/Projekte/rats-transscript/venv/lib/python3.10/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/home/jk/Projekte/rats-transscript/venv/lib/python3.10/site-packages/httpx/_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
  File "/home/jk/Projekte/rats-transscript/venv/lib/python3.10/site-packages/hishel/_sync/_transports.py", line 187, in handle_request
    response = self._transport.handle_request(request)
  File "/home/jk/Projekte/rats-transscript/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 227, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/jk/Projekte/rats-transscript/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.PoolTimeout
``

**Comment by karosis88** [comment]
Hi @hnesk, thank you for this clean issue.

It's a very good catch. I assumed that httpx.HTTPTransport uses ConnectionPool.request(), which automatically closes after it's read, but not.

Now we have to somehow handle such cases. So the first thing that comes to mind is to wrap the original stream like httpx and httpcore do in general, and that's how it works.

Add FakeStream class

```python
class FakeStream(ResponseStream):

    def __init__(self, httpcore_stream: tp.Iterable[bytes], real_stream: tp.Iterable[bytes]):
        self._httpcore_stream = httpcore_stream  # stream which fake_stream function gives
        self._real_sream = real_stream  # the original stream


    def close(self) -> None:
        if hasattr(self._real_sream, "close"):
            self._real_sream.close()
```

replace ResponseStream with FakeStream
```python
# old
stream=ResponseStream(fake_stream(full_response.content))

# new
stream=FakeStream(fake_stream(full_response.content), full_response.stream)
```
This solution works for me and also passes the tests, so let's double-check it and resolve this issue.

**Comment by karosis88** [comment]
Because hishel does not support streaming responses, we can also close the httpcore stream immediately after reading it in CacheTransport.

What do you think about that @hnesk?

**Comment by hnesk** [comment]
That's up for you to decide. 
I'm not deep enough into the internals of httpx to decide, and was glad to find a reproducer, but that's were my expertise ends ;)

**Comment by karosis88** [comment]
Thank you so much, #83 has resolved this issue.

**Comment by hnesk** [comment]
Yes, it has. Thank you!
